export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const UNSUCCESSFUL_LOGIN = 'UNSUCCESSFUL_LOGIN';
export const SUCCESSFUL_REGISTERED = 'SUCCESSFUL_REGISTERED';
export const SUCCESSFUL_LOADED_ARTICLES = 'SUCCESSFUL_LOADED_ARTICLES';
export const SUCCESSFUL_ADDED_ARTICLES = 'SUCCESSFUL_ADDED_ARTICLES';
export const SUCCESSFUL_LOG_OUT = 'SUCCESSFUL_LOG_OUT';
export const ALREADY_LOGIN_SUCCESS = 'ALREADY_LOGIN_SUCCESS';

